// <auto-generated />
using System;
using JetPay.TonWatcher.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JetPay.TonWatcher.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251022144940_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JetPay.TonWatcher.Domain.Entities.ShardBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Seqno")
                        .HasColumnType("bigint");

                    b.Property<long>("Shard")
                        .HasColumnType("bigint");

                    b.Property<int>("Workchain")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Seqno");

                    b.ToTable("ShardBlocks");
                });

            modelBuilder.Entity("JetPay.TonWatcher.Domain.Entities.TrackedAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Account")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsTrackingActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Workchain")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TrackedAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
