// <auto-generated />
using System;
using JetPay.TonWatcher.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JetPay.TonWatcher.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JetPay.TonWatcher.Data.Models.MasterchainBlock", b =>
                {
                    b.Property<long>("Seqno")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Seqno");

                    b.HasIndex("IsProcessed");

                    b.ToTable("MasterchainBlocks");
                });

            modelBuilder.Entity("JetPay.TonWatcher.Data.Models.TrackedAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)");

                    b.Property<bool>("IsTrackingActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("TrackedAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
